### ISSUE TITLE
Error while using native funtion of Leekloud

### ISSUE THREAD

**Issue by 4sStylZ** [GuimDev/LeeKloud#5]
Hi, / Salut, 

I have this result when I try to use the command line function of Leekloud : 

```
------------------------------------------------------------------------------------------------------------- LeeKloud 2.0.0 -------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------Programme proposé par @GuimDev, certaines parties du code sont sous licence.-------------------------------------------------------------------------------
------------------------------------------------------------------------------------- En cas de problème contactez-moi sur le forum ou MP HorsSujet. -------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Emplacement : D:\Projects\4sStylZ-II-AI\

Connexion réussie.

Obtention de la liste des scripts :
>> Téléchargements...

[17:10:00] - requête pour Sans Titre.
- Sans Titre[hs271813].js.lk.
--- ETAT : Identique
> .create test
Erreur vraiment fatale !

ReferenceError: $ is not defined
    at useCommande (D:\Projects\LeeKloud\LeeModule\main.js:1074:4)
    at EventEmitter.<anonymous> (D:\Projects\LeeKloud\LeeModule\main.js:1357:3)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Interface.<anonymous> (D:\Projects\LeeKloud\LeeModule\nodeReadline.js:71:19)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._line (readline.js:629:8)
    at Interface._ttyWrite (readline.js:910:14)

L'erreur a été reportée dans le fichier :
D:\Projects\4sStylZ-II-AI\.LeeKloud\rapport.log
```

Any idea of the reason ?

**Comment by GuimDev** [comment]
Je n'ai pas finis de recoder la plus part des commandes

**Comment by GuimDev** [comment]
Faute de réponse sur le forum, j'ai laissé un peu Leekloud de côté

**Comment by 4sStylZ** [comment]
Ok. Je comprend ta prise de distance.

Par contre je ne comprend pas les autres :) C’est tellement cool de pouvoir versionner son code et de travailler avec sublime.
